--- Inhibitor object properties.
---@class inhib.obj
---@field public type number
---@field public index number
---@field public team number
---@field public networkID number
---@field public networkID32 number
---@field public name string
---@field public x number
---@field public y number
---@field public z number
---@field public pos vec3
---@field public pos2D vec2
---@field public isOnScreen boolean
---@field public selectionHeight number
---@field public selectionRadius number
---@field public boundingRadius number
---@field public overrideCollisionRadius number
---@field public pathfindingCollisionRadius number
---@field public minBoundingBox vec3
---@field public maxBoundingBox vec3
---@field public isDead boolean
---@field public isVisible boolean
---@field public deathTime number
---@field public health number
---@field public maxHealth number
---@field public allShield number
---@field public isTargetable boolean
---@field public isTargetableToTeamFlags number

---@type inhib.obj
_G.inhib = {}